apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
  namespace: examples
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flask-hello-world
  ports:
    - port: 3001
      targetPort: 3001
