apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
  namespace: examples
  labels:
    app.kubernetes.io/name: go-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-hello-world
    spec:
      containers:
      - name: go-hello-world
        image: localhost:5005/go-hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
