# Creating a local cluster with multiple nodes to prevent
# podAntiAffinity constraints from breaking apps we make
# changes to and redeploy.
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: my-cluster
  nodes:
  - role: control-plane
  - role: worker
  - role: worker
  
