# Creating a local cluster with multiple nodes to prevent
# podAntiAffinity constraints from breaking apps we make
# changes to and redeploy.
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: my-cluster
  networking:
    apiServerAddress: 127.0.0.1
    apiServerPort: 6443
    disableDefaultCNI: true
    kubeProxyMode: "ipvs"
    podSubnet: "10.96.0.0/16"
    serviceSubnet: "10.98.0.0/16"
  nodes:
  - role: control-plane
    extraMounts:
    - hostPath: /opt/cni/bin
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: /opt/cni/bin
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: /opt/cni/bin
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: /opt/cni/bin
      containerPath: /opt/cni/bin
  
