apiVersion: v1
kind: Service
metadata:
  name: express-hello-world
  namespace: examples
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: express-hello-world
  ports:
    - port: 3000
      targetPort: 3000
