apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: example-database-backup-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "example-database-backup.home.arpa"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "example-database-backup.home.arpa"
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example-database-backup-https-destination
spec:
  host: myminio-console
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-database-backup-virtualservice
spec:
  hosts:
  - "example-database-backup.home.arpa"
  gateways:
  - example-database-backup-gateway
  http:
  - route:
    - destination:
        host: myminio-console
        port:
          number: 9443
