namespace: example-database

helmGlobals:
  chartHome: helm

secretGenerator:
- name: example-database-backup-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: tenant
  valuesInline:
    namespace: example-database
    secrets:
      name: myminio-env-configuration
      accessKey: minio
      secretKey: minio123
    tenant:
      pools:
        - name: 'pool-0'
          containerSecurityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          securityContext:
            fsGroup: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          size: '10Gi'
          storageClassName: 'standard'
      buckets:
        - name: 'example-database-backup'

  version:
  # Find the latest stable at https://github.com/minio/operator/tree/master/helm/tenant
  # https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-helm.html
  releaseName: example-database-backup
  repo: https://operator.min.io/
  version: 5.0.6

resources:
- example-database-backup-proxy.yaml
- example-database.yaml
