namespace: example-database

secretGenerator:
- name: example-database-backup-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
- example-database-backup.yaml
- example-database-backup-proxy.yaml
- example-database.yaml
