namespace: identity

helmGlobals:
  chartHome: helm

secretGenerator:
- name: identity-database-backup-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: tenant
  namespace: identity
  valuesInline:
    secrets:
      name: myminio-env-configuration
      accessKey: minio
      secretKey: minio123
    tenant:
      pools:
        - name: 'pool-0'
          containerSecurityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          securityContext:
            fsGroup: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          size: '10Gi'
          storageClassName: 'standard'
      buckets:
        - name: 'identity-backup'

  version:
  # Find the latest stable at https://github.com/minio/operator/tree/master/helm/tenant
  # https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-helm.html
  releaseName: identity-backup
  repo: https://operator.min.io/
  version: 5.0.6

resources:
  - identity-backup-proxy.yaml
  - identity-database.yaml
  - keycloak.yaml
  - keycloak-proxy.yaml

patches:
  - path: delete-loadbalancer.yaml
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: HOSTNAME
          value: "identity.home.arpa"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_VENDOR
          value: "postgres"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: host
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: port
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_USER
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: user
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: password
    target:
      kind: Deployment
      name: keycloak
