namespace: identity

secretGenerator:
- name: identity-database-backup-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
  - identity-backup.yaml
  - identity-backup-proxy.yaml
  - identity-database.yaml
  - keycloak.yaml
  - keycloak-proxy.yaml

patches:
  - path: delete-loadbalancer.yaml
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: HOSTNAME
          value: "identity.home.arpa"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_VENDOR
          value: "postgres"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: host
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: port
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_USER
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: user
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-database-pguser-identity-database
              key: password
    target:
      kind: Deployment
      name: keycloak
