apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: console-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "storage.home.arpa"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "storage.home.arpa"
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: console-virtualservice
spec:
  hosts:
  - "storage.home.arpa"
  gateways:
  - console-gateway
  http:
  - route:
    - destination:
        host: console
        port:
          number: 9090
