apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    name: identity
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    name: network
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
  labels:
    name: secrets
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-main
  labels:
    name: storage-main
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-operator
  labels:
    name: storage-operator
    istio-injection: disabled
