apiVersion: v1
kind: Namespace
metadata:
  name: delivery
  labels:
    name: delivery
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    name: identity
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    name: network
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    name: data
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: policy
  labels:
    name: policy
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
  labels:
    name: secrets
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    istio-injection: disabled
