apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    name: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
  labels:
    name: secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-operator
  labels:
    name: storage-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-main
  labels:
    name: storage-main
