namespace: secrets

helmGlobals:
  chartHome: helm

helmCharts:
- name: vault
  valuesInline:
    namespace: secrets
    server:
      dev:
        enabled: true
  version:
  # Find the latest stable at https://developer.hashicorp.com/vault/docs/platform/k8s/helm
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.24.1

resources:
  - vault-proxy.yaml
