namespace: network

resources:
  # Version tag needs to match Helm charts below
  - https://raw.githubusercontent.com/istio/istio/1.18.1/manifests/charts/base/crds/crd-all.gen.yaml

helmGlobals:
  chartHome: helm

# Find the latest version at https://github.com/istio/istio/releases
helmCharts:

- name: base
  valuesInline:
    defaultRevision: default
    global:
      istioNamespace: network
    profile: default
    validationURL: "https://istiod.network.svc:15017/validate"
  releaseName: istio-base
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.18.1

- name: istiod
  namespace: network
  valuesInline:
    defaultRevision: default
    global:
      istioNamespace: network
    meshConfig.ingressService: istio-ingressgateway
    meshConfig.ingressSelector: istio-ingressgateway
    meshConfig.rootNamespace: network
    namespace: network
    pilot.seccompProfile.type: RuntimeDefault
    watchedNamespaces: network
  releaseName: istio-istiod
  repo: https://istio-release.storage.googleapis.com/charts/
  version: 1.18.1

- name: gateway
  namespace: network
  valuesInline:
    global:
      istioNamespace: network
  releaseName: istio-ingressgateway
  repo: https://istio-release.storage.googleapis.com/charts/
  version: 1.18.1

